export const ADD_CONTACT= "ADD_CONTACT";
export const DELETE_CONTACT="DELETE_CONTACT";
export const EDIT_CONTACT = "EDIT_CONTACT";
export const FETCH_DATA = 'FETCH_DATA';
export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS';
export const FETCH_DATA_FAILED = 'FETCH_DATA_FAILED';